### ISSUE TITLE
关于code编写

### ISSUE THREAD

**Issue by fuleicug** [ChenfaZheng/PINN-for-wave-equation#1]
您好，
     我是中国地质大学（武汉）地空学院的傅磊，我对您这个PINN-for-wave-equation非常感兴趣，您推荐的那篇文章我也看了，说实话没咋看懂~ 请问您有更加详细的关于coding的说明吗？谢谢！

**Comment by ChenfaZheng** [comment]
您好，
我更新了一个demo对代码进行了简要介绍，希望对您有帮助~
