### ISSUE TITLE
你好，请问对于gauusian-2d.py程序的自然边界是否设置有点问题？

### ISSUE THREAD

**Issue by Honghui-Du** [ChenfaZheng/PINN-for-wave-equation#2]
因为我输出自然边界点Xb，结果显示为一条直线，但是对于二维问题，自然边界应该是由（x,t）组成的二维平面？
![image](https://user-images.githubusercontent.com/116039765/208221650-e71f8f10-0e79-4616-a038-e6dac0b3975d.png)

祝好
Honghui

**Comment by ChenfaZheng** [comment]
你好，
如果求解的问题不同，定义的边界条件亦不同，但可以根据需要类比地进行修改。关于代码中对应的定义请见更新的[description](https://github.com/ChenfaZheng/PINN-for-wave-equation/blob/main/archive/description.md)

祝好
